export enum NOTIFICATION_EVENTS {
  // CHAT
  DELETED_CHAT_MESSAGE = "DELETED_CHAT_MESSAGE",
  NEW_CHAT_MESSAGE = "NEW_CHAT_MESSAGE",

  // OTHER
  NEW_POST = "NEW_POST",

  NEW_FOLLOWER = "NEW_FOLLOWER",
  NEW_COMMENT_ON_POST = "NEW_COMMENT_ON_POST",
  NEW_LIKE_ON_POST = "NEW_LIKE_ON_POST",

  NEW_MENTION_IN_POST = "NEW_MENTION_IN_POST",
  NEW_MENTION_IN_POST_COMMENT = "NEW_MENTION_IN_POST_COMMENT",
}
