export enum NOTIFICATION_EVENTS {
  // CHAT
  DELETED_CHAT_MESSAGE = "DELETED_CHAT_MESSAGE",
  NEW_CHAT_MESSAGE = "NEW_CHAT_MESSAGE",

  // USER NOTIFICATION
  NEW_COMMENT_ON_POST = "NEW_COMMENT_ON_POST",
  CANCELED_NEW_COMMENT_ON_POST = "CANCELED_NEW_COMMENT_ON_POST",

  NEW_FOLLOWER = "NEW_FOLLOWER",
  CANCELED_NEW_FOLLOWER = "CANCELED_NEW_FOLLOWER",

  NEW_LIKE_ON_POST = "NEW_LIKE_ON_POST",
  CANCELED_NEW_LIKE_ON_POST = "CANCELED_NEW_LIKE_ON_POST",

  NEW_TAG_IN_PUBLISHED_ITEM_COMMENT = "NEW_TAG_IN_PUBLISHED_ITEM_COMMENT",
  CANCELED_NEW_TAG_IN_PUBLISHED_ITEM_COMMENT = "CANCELED_NEW_TAG_IN_PUBLISHED_ITEM_COMMENT",


  // OTHER
  NEW_POST = "NEW_POST",
}
