steps:
- id: 'kupo-beta-frontend steps'
  name: 'hashicorp/terraform:1.3.5'
  entrypoint: 'sh'
  secretEnv: [
        'API_BASE_URL',
        'API_WEBSOCKET_URL',
        'NODE_OPTIONS',
  ]
  args:
  - '-c'
  - |
    set -x
    echo "branch $BRANCH_NAME"
    if [ ! -z "$BRANCH_NAME" -a -d "terraform/environments/$BRANCH_NAME/" ]; then
      cd terraform/environments/$BRANCH_NAME
      printf "$$API_BASE_URL $$API_WEBSOCKET_URL $$NODE_OPTIONS\n" > $BRANCH_NAME.auto.tfvars
      echo "run init"
      terraform init
      echo "run validate"
      terraform validate
      echo "run plan"
      terraform plan -out terraform.plan
      terraform apply -auto-approve terraform.plan
    else
      dir="terraform/environments/beta/frontend"
      cd ${dir}
      env=${dir%*/}
      env=${env#*/}
      echo ""
      echo "******************** TERRAFORM PLAN *******************"
      echo "************ Environment: ${env} ************"
      echo "*******************************************************"
      terraform init
      terraform validate
      terraform plan || exit 1
      cd ../../
    fi
availableSecrets:
  secretManager:
    - env: 'API_BASE_URL'
      versionName: 'projects/955075264221/secrets/beta_frontend_API_BASE_URL/versions/latest'
    - env: 'API_WEBSOCKET_URL'    
      versionName: 'projects/955075264221/secrets/beta_frontend_API_WEBSOCKET_URL/versions/latest'
    - env: 'NODE_OPTIONS'
      versionName: 'projects/955075264221/secrets/beta_frontend_NODE_OPTIONS/versions/latest'