//
// AddModeratorToPublishingChannelRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddModeratorToPublishingChannelRequestBody: Codable, JSONEncodable, Hashable {

    public var publishingChannelId: String
    public var moderatorUserId: String

    public init(publishingChannelId: String, moderatorUserId: String) {
        self.publishingChannelId = publishingChannelId
        self.moderatorUserId = moderatorUserId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannelId
        case moderatorUserId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannelId, forKey: .publishingChannelId)
        try container.encode(moderatorUserId, forKey: .moderatorUserId)
    }
}

