//
// AuthFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AuthFailedReason: String, Codable, CaseIterable {
    case wrongPassword = "Wrong Password"
    case unknownCause = "Unknown Cause"
    case noRefreshTokenFound = "No Refresh Token Found"
    case failedToValidateToken = "Failed To Validate Token"
    case failedToGenerateAccessToken = "Failed To Generate Access Token"
    case youMustBeLoggedIn = "You Must Be Logged In"
    case illegalAccess = "Illegal Access"
    case accountLocked = "Account Locked"
}
