//
// ClientUserDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientUserDetails: Codable, JSONEncodable, Hashable {

    public var followingCommunities: RenderableUserFollowers
    public var followerRequests: RenderableUserFollowers

    public init(followingCommunities: RenderableUserFollowers, followerRequests: RenderableUserFollowers) {
        self.followingCommunities = followingCommunities
        self.followerRequests = followerRequests
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case followingCommunities
        case followerRequests
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(followingCommunities, forKey: .followingCommunities)
        try container.encode(followerRequests, forKey: .followerRequests)
    }
}

