//
// CreateChatMessageRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateChatMessageRequestBody: Codable, JSONEncodable, Hashable {

    public var chatMessageText: String
    public var chatRoomId: String

    public init(chatMessageText: String, chatRoomId: String) {
        self.chatMessageText = chatMessageText
        self.chatRoomId = chatRoomId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatMessageText
        case chatRoomId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatMessageText, forKey: .chatMessageText)
        try container.encode(chatRoomId, forKey: .chatRoomId)
    }
}

