//
// CreatePostSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePostSuccess: Codable, JSONEncodable, Hashable {

    public var renderablePost: RenderablePost

    public init(renderablePost: RenderablePost) {
        self.renderablePost = renderablePost
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case renderablePost
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(renderablePost, forKey: .renderablePost)
    }
}

