//
// CreateShopItemSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateShopItemSuccess: Codable, JSONEncodable, Hashable {

    public var renderableShopItem: RenderableShopItem

    public init(renderableShopItem: RenderableShopItem) {
        self.renderableShopItem = renderableShopItem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case renderableShopItem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(renderableShopItem, forKey: .renderableShopItem)
    }
}

