//
// CreateChatMessageInNewChatRoomSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateChatMessageInNewChatRoomSuccess: Codable, JSONEncodable, Hashable {

    public var chatRoomId: String

    public init(chatRoomId: String) {
        self.chatRoomId = chatRoomId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatRoomId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatRoomId, forKey: .chatRoomId)
    }
}

