//
// CreatePublishedItemCommentFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CreatePublishedItemCommentFailedReason: String, Codable, CaseIterable {
    case unknownReason = "UNKNOWN_REASON"
}
