//
// CreatePostFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CreatePostFailedReason: String, Codable, CaseIterable {
    case unknownCause = "Unknown Cause"
    case expirationTimestampIsInPast = "Expiration Timestamp is in Past"
    case scheduledPublicationTimestampIsInPast = "Scheduled Publication Timestamp is in Past"
}
