//
// CreatePublishingChannelSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePublishingChannelSuccess: Codable, JSONEncodable, Hashable {

    public var publishingChannelId: String
    public var ownerUserId: String
    public var name: String
    public var description: String

    public init(publishingChannelId: String, ownerUserId: String, name: String, description: String) {
        self.publishingChannelId = publishingChannelId
        self.ownerUserId = ownerUserId
        self.name = name
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannelId
        case ownerUserId
        case name
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannelId, forKey: .publishingChannelId)
        try container.encode(ownerUserId, forKey: .ownerUserId)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
    }
}

