//
// CreatePublishedItemCommentSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePublishedItemCommentSuccess: Codable, JSONEncodable, Hashable {

    public var postComment: RenderablePublishedItemComment

    public init(postComment: RenderablePublishedItemComment) {
        self.postComment = postComment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case postComment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(postComment, forKey: .postComment)
    }
}

