//
// CreateChatMessageInNewRoomRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateChatMessageInNewRoomRequestBody: Codable, JSONEncodable, Hashable {

    public var chatMessageText: String
    public var userIds: [String]

    public init(chatMessageText: String, userIds: [String]) {
        self.chatMessageText = chatMessageText
        self.userIds = userIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatMessageText
        case userIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatMessageText, forKey: .chatMessageText)
        try container.encode(userIds, forKey: .userIds)
    }
}

