//
// CreatePublishedItemCommentRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePublishedItemCommentRequestBody: Codable, JSONEncodable, Hashable {

    public var publishedItemId: String
    public var text: String

    public init(publishedItemId: String, text: String) {
        self.publishedItemId = publishedItemId
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItemId
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItemId, forKey: .publishedItemId)
        try container.encode(text, forKey: .text)
    }
}

