//
// CreateChatMessageInNewChatRoomFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CreateChatMessageInNewChatRoomFailedReason: String, Codable, CaseIterable {
    case unknownCause = "Unknown Cause"
    case roomAlreadyExists = "Room Already Exists"
}
