//
// DeleteChatMessageRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteChatMessageRequestBody: Codable, JSONEncodable, Hashable {

    public var chatMessageId: String

    public init(chatMessageId: String) {
        self.chatMessageId = chatMessageId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatMessageId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatMessageId, forKey: .chatMessageId)
    }
}

