//
// DeleteShopItemRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteShopItemRequestBody: Codable, JSONEncodable, Hashable {

    public var publishedItemId: String

    public init(publishedItemId: String) {
        self.publishedItemId = publishedItemId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItemId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItemId, forKey: .publishedItemId)
    }
}

