//
// EitherTypeSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum EitherTypeSuccess: String, Codable, CaseIterable {
    case success = "success"
}
