//
// EitherTypeFailure.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum EitherTypeFailure: String, Codable, CaseIterable {
    case failure = "failure"
}
