//
// ElevateUserToAdminFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ElevateUserToAdminFailedReason: String, Codable, CaseIterable {
    case userNotFound = "User Not Found"
    case illegalAccess = "ILLEGAL_ACCESS"
}
