//
// ElevateUserToAdminRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ElevateUserToAdminRequestBody: Codable, JSONEncodable, Hashable {

    public var userIdElevatedToAdmin: String

    public init(userIdElevatedToAdmin: String) {
        self.userIdElevatedToAdmin = userIdElevatedToAdmin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userIdElevatedToAdmin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userIdElevatedToAdmin, forKey: .userIdElevatedToAdmin)
    }
}

