//
// FileDescriptor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FileDescriptor: Codable, JSONEncodable, Hashable {

    public var blobFileKey: String
    public var mimeType: String

    public init(blobFileKey: String, mimeType: String) {
        self.blobFileKey = blobFileKey
        self.mimeType = mimeType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blobFileKey
        case mimeType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blobFileKey, forKey: .blobFileKey)
        try container.encode(mimeType, forKey: .mimeType)
    }
}

