//
// FollowPublishingChannelRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FollowPublishingChannelRequestBody: Codable, JSONEncodable, Hashable {

    public var publishingChannelIdBeingFollowed: String

    public init(publishingChannelIdBeingFollowed: String) {
        self.publishingChannelIdBeingFollowed = publishingChannelIdBeingFollowed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannelIdBeingFollowed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannelIdBeingFollowed, forKey: .publishingChannelIdBeingFollowed)
    }
}

