//
// FollowAllRequestsDecision.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FollowAllRequestsDecision: String, Codable, CaseIterable {
    case accept = "accept"
    case reject = "reject"
}
