//
// FollowingStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FollowingStatus: String, Codable, CaseIterable {
    case isFollowing = "is_following"
    case notFollowing = "not_following"
    case pending = "pending"
}
