//
// GenericResponseFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GenericResponseFailedReason: String, Codable, CaseIterable {
    case badRequest = "BAD_REQUEST"
    case databaseTransactionError = "DATABASE_TRANSACTION_ERROR"
    case fastCacheTransactionError = "FAST_CACHE_TRANSACTION_ERROR"
    case paymentProcessorError = "PAYMENT_PROCESSOR_ERROR"
    case emailServiceError = "EMAIL_SERVICE_ERROR"
    case blobStorageError = "BLOB_STORAGE_ERROR"
    case improperUseOfFunction = "IMPROPER_USE_OF_FUNCTION"
    case idempotentycyTokenAlreadyEncountered = "IDEMPOTENTYCY_TOKEN_ALREADY_ENCOUNTERED"
}
