//
// GetCreditCardsStoredByUserIdSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCreditCardsStoredByUserIdSuccess: Codable, JSONEncodable, Hashable {

    public var cards: [CreditCardSummary]

    public init(cards: [CreditCardSummary]) {
        self.cards = cards
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cards
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cards, forKey: .cards)
    }
}

