//
// GetChatRoomByIdSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetChatRoomByIdSuccess: Codable, JSONEncodable, Hashable {

    public var chatRoom: RenderableChatRoomWithJoinedUsers

    public init(chatRoom: RenderableChatRoomWithJoinedUsers) {
        self.chatRoom = chatRoom
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatRoom
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatRoom, forKey: .chatRoom)
    }
}

