//
// GetFollowerRequestsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetFollowerRequestsSuccess: Codable, JSONEncodable, Hashable {

    public var users: [RenderableUser]
    public var previousPageCursor: String?
    public var nextPageCursor: String?

    public init(users: [RenderableUser], previousPageCursor: String? = nil, nextPageCursor: String? = nil) {
        self.users = users
        self.previousPageCursor = previousPageCursor
        self.nextPageCursor = nextPageCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case previousPageCursor
        case nextPageCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(users, forKey: .users)
        try container.encodeIfPresent(previousPageCursor, forKey: .previousPageCursor)
        try container.encodeIfPresent(nextPageCursor, forKey: .nextPageCursor)
    }
}

