//
// GetPublishedItemsScheduledByUserRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishedItemsScheduledByUserRequestBody: Codable, JSONEncodable, Hashable {

    public var rangeStartTimestamp: Double
    public var rangeEndTimestamp: Double
    public var publishedItemType: PublishedItemType?

    public init(rangeStartTimestamp: Double, rangeEndTimestamp: Double, publishedItemType: PublishedItemType? = nil) {
        self.rangeStartTimestamp = rangeStartTimestamp
        self.rangeEndTimestamp = rangeEndTimestamp
        self.publishedItemType = publishedItemType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rangeStartTimestamp
        case rangeEndTimestamp
        case publishedItemType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rangeStartTimestamp, forKey: .rangeStartTimestamp)
        try container.encode(rangeEndTimestamp, forKey: .rangeEndTimestamp)
        try container.encodeIfPresent(publishedItemType, forKey: .publishedItemType)
    }
}

