//
// GetPageOfUsersFollowingUserIdRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPageOfUsersFollowingUserIdRequestBody: Codable, JSONEncodable, Hashable {

    public var userIdBeingFollowed: String
    public var cursor: String?
    public var pageSize: Double

    public init(userIdBeingFollowed: String, cursor: String? = nil, pageSize: Double) {
        self.userIdBeingFollowed = userIdBeingFollowed
        self.cursor = cursor
        self.pageSize = pageSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userIdBeingFollowed
        case cursor
        case pageSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userIdBeingFollowed, forKey: .userIdBeingFollowed)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
    }
}

