//
// GetPublishedItemsScheduledByUserSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishedItemsScheduledByUserSuccess: Codable, JSONEncodable, Hashable {

    public var publishedItems: [RenderablePublishedItem]

    public init(publishedItems: [RenderablePublishedItem]) {
        self.publishedItems = publishedItems
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItems
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItems, forKey: .publishedItems)
    }
}

