//
// GetPageOfUsersFollowedByUserIdRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPageOfUsersFollowedByUserIdRequestBody: Codable, JSONEncodable, Hashable {

    public var userIdDoingFollowing: String
    public var cursor: String?
    public var pageSize: Double

    public init(userIdDoingFollowing: String, cursor: String? = nil, pageSize: Double) {
        self.userIdDoingFollowing = userIdDoingFollowing
        self.cursor = cursor
        self.pageSize = pageSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userIdDoingFollowing
        case cursor
        case pageSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userIdDoingFollowing, forKey: .userIdDoingFollowing)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
    }
}

