//
// GetPublishedItemsFromAllFollowingsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishedItemsFromAllFollowingsSuccess: Codable, JSONEncodable, Hashable {

    public var publishedItems: [RenderablePublishedItem]
    public var previousPageCursor: String?
    public var nextPageCursor: String?

    public init(publishedItems: [RenderablePublishedItem], previousPageCursor: String? = nil, nextPageCursor: String? = nil) {
        self.publishedItems = publishedItems
        self.previousPageCursor = previousPageCursor
        self.nextPageCursor = nextPageCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItems
        case previousPageCursor
        case nextPageCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItems, forKey: .publishedItems)
        try container.encodeIfPresent(previousPageCursor, forKey: .previousPageCursor)
        try container.encodeIfPresent(nextPageCursor, forKey: .nextPageCursor)
    }
}

