//
// GetPublishedItemsByUsernameFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetPublishedItemsByUsernameFailedReason: String, Codable, CaseIterable {
    case unknownCause = "Unknown Cause"
    case thisUserQuoteSPostsArePrivate = "This User's Posts Are Private"
    case userNotFound = "User Not Found"
}
