//
// GetPublishingChannelsFollowedByUserIdSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishingChannelsFollowedByUserIdSuccess: Codable, JSONEncodable, Hashable {

    public var publishingChannels: [RenderablePublishingChannel]
    public var previousPageCursor: String?
    public var nextPageCursor: String?

    public init(publishingChannels: [RenderablePublishingChannel], previousPageCursor: String? = nil, nextPageCursor: String? = nil) {
        self.publishingChannels = publishingChannels
        self.previousPageCursor = previousPageCursor
        self.nextPageCursor = nextPageCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannels
        case previousPageCursor
        case nextPageCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannels, forKey: .publishingChannels)
        try container.encodeIfPresent(previousPageCursor, forKey: .previousPageCursor)
        try container.encodeIfPresent(nextPageCursor, forKey: .nextPageCursor)
    }
}

