//
// GetPageOfAllPublishedItemsFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetPageOfAllPublishedItemsFailedReason: String, Codable, CaseIterable {
    case illegalAccess = "ILLEGAL_ACCESS"
    case unknownCause = "Unknown Cause"
}
