//
// GetPageOfNotificationsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPageOfNotificationsSuccess: Codable, JSONEncodable, Hashable {

    public var userNotifications: [RenderableUserNotification]
    public var previousPageCursor: String?
    public var nextPageCursor: String?

    public init(userNotifications: [RenderableUserNotification], previousPageCursor: String? = nil, nextPageCursor: String? = nil) {
        self.userNotifications = userNotifications
        self.previousPageCursor = previousPageCursor
        self.nextPageCursor = nextPageCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userNotifications
        case previousPageCursor
        case nextPageCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userNotifications, forKey: .userNotifications)
        try container.encodeIfPresent(previousPageCursor, forKey: .previousPageCursor)
        try container.encodeIfPresent(nextPageCursor, forKey: .nextPageCursor)
    }
}

