//
// GetPasswordResetEmailFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetPasswordResetEmailFailedReason: String, Codable, CaseIterable {
    case tooManyAttempts = "Too Many Attempts"
}
