//
// GetPublishedItemsInPublishingChannelRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishedItemsInPublishingChannelRequestBody: Codable, JSONEncodable, Hashable {

    public var publishingChannelName: String
    public var cursor: String?
    public var pageSize: Double
    public var publishedItemType: PublishedItemType?

    public init(publishingChannelName: String, cursor: String? = nil, pageSize: Double, publishedItemType: PublishedItemType? = nil) {
        self.publishingChannelName = publishingChannelName
        self.cursor = cursor
        self.pageSize = pageSize
        self.publishedItemType = publishedItemType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannelName
        case cursor
        case pageSize
        case publishedItemType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannelName, forKey: .publishingChannelName)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
        try container.encodeIfPresent(publishedItemType, forKey: .publishedItemType)
    }
}

