//
// GetPublishingChannelsFollowedByUserIdRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishingChannelsFollowedByUserIdRequestBody: Codable, JSONEncodable, Hashable {

    public var cursor: String?
    public var pageSize: Double
    public var areFollowsPending: Bool

    public init(cursor: String? = nil, pageSize: Double, areFollowsPending: Bool) {
        self.cursor = cursor
        self.pageSize = pageSize
        self.areFollowsPending = areFollowsPending
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cursor
        case pageSize
        case areFollowsPending
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
        try container.encode(areFollowsPending, forKey: .areFollowsPending)
    }
}

