//
// GetPageOfAllPublishedItemsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPageOfAllPublishedItemsSuccess: Codable, JSONEncodable, Hashable {

    public var renderablePublishedItems: [RenderablePublishedItem]
    public var previousPageCursor: String?
    public var nextPageCursor: String?

    public init(renderablePublishedItems: [RenderablePublishedItem], previousPageCursor: String? = nil, nextPageCursor: String? = nil) {
        self.renderablePublishedItems = renderablePublishedItems
        self.previousPageCursor = previousPageCursor
        self.nextPageCursor = nextPageCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case renderablePublishedItems
        case previousPageCursor
        case nextPageCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(renderablePublishedItems, forKey: .renderablePublishedItems)
        try container.encodeIfPresent(previousPageCursor, forKey: .previousPageCursor)
        try container.encodeIfPresent(nextPageCursor, forKey: .nextPageCursor)
    }
}

