//
// GetPublishingChannelSubmissionsSuccessPublishedSubmissionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishingChannelSubmissionsSuccessPublishedSubmissionsInner: Codable, JSONEncodable, Hashable {

    public var publishedItem: RenderablePublishedItem
    public var submissionId: String

    public init(publishedItem: RenderablePublishedItem, submissionId: String) {
        self.publishedItem = publishedItem
        self.submissionId = submissionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItem
        case submissionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItem, forKey: .publishedItem)
        try container.encode(submissionId, forKey: .submissionId)
    }
}

