//
// GetPublishingChannelSubmissionsRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishingChannelSubmissionsRequestBody: Codable, JSONEncodable, Hashable {

    public var cursor: String?
    public var pageSize: Double
    public var publishingChannelId: String

    public init(cursor: String? = nil, pageSize: Double, publishingChannelId: String) {
        self.cursor = cursor
        self.pageSize = pageSize
        self.publishingChannelId = publishingChannelId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cursor
        case pageSize
        case publishingChannelId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
        try container.encode(publishingChannelId, forKey: .publishingChannelId)
    }
}

