//
// GetPublishingChannelByNameSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishingChannelByNameSuccess: Codable, JSONEncodable, Hashable {

    public var publishingChannel: RenderablePublishingChannel

    public init(publishingChannel: RenderablePublishingChannel) {
        self.publishingChannel = publishingChannel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannel, forKey: .publishingChannel)
    }
}

