//
// GetPageOfChatMessagesFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetPageOfChatMessagesFailedReason: String, Codable, CaseIterable {
    case unknownCause = "Unknown Cause"
    case illegalAccess = "ILLEGAL_ACCESS"
}
