//
// GetPageOfChatRoomsRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPageOfChatRoomsRequestBody: Codable, JSONEncodable, Hashable {

    public var cursor: String?
    public var pageSize: Double
    public var query: String?

    public init(cursor: String? = nil, pageSize: Double, query: String? = nil) {
        self.cursor = cursor
        self.pageSize = pageSize
        self.query = query
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cursor
        case pageSize
        case query
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
        try container.encodeIfPresent(query, forKey: .query)
    }
}

