//
// GetPublishingChannelByNameFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetPublishingChannelByNameFailedReason: String, Codable, CaseIterable {
    case unknownCause = "Unknown Cause"
    case publishingChannelNameNotFound = "PublishingChannelNameNotFound"
    case channelOwnerNotFound = "ChannelOwnerNotFound"
}
