//
// GetPublishedItemByIdSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPublishedItemByIdSuccess: Codable, JSONEncodable, Hashable {

    public var publishedItem: GetPublishedItemByIdSuccessPublishedItem

    public init(publishedItem: GetPublishedItemByIdSuccessPublishedItem) {
        self.publishedItem = publishedItem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItem, forKey: .publishedItem)
    }
}

