//
// GetPageOfNotificationsRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPageOfNotificationsRequestBody: Codable, JSONEncodable, Hashable {

    public var cursor: String?
    public var pageSize: Double
    public var isUserReadingNotifications: Bool?

    public init(cursor: String? = nil, pageSize: Double, isUserReadingNotifications: Bool? = nil) {
        self.cursor = cursor
        self.pageSize = pageSize
        self.isUserReadingNotifications = isUserReadingNotifications
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cursor
        case pageSize
        case isUserReadingNotifications
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
        try container.encodeIfPresent(isUserReadingNotifications, forKey: .isUserReadingNotifications)
    }
}

