//
// GetPageOfChatMessagesRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPageOfChatMessagesRequestBody: Codable, JSONEncodable, Hashable {

    public var chatRoomId: String
    public var cursor: String?
    public var pageSize: Double

    public init(chatRoomId: String, cursor: String? = nil, pageSize: Double) {
        self.chatRoomId = chatRoomId
        self.cursor = cursor
        self.pageSize = pageSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatRoomId
        case cursor
        case pageSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatRoomId, forKey: .chatRoomId)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
    }
}

