//
// GetRecommendedPublishingChannelsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRecommendedPublishingChannelsSuccess: Codable, JSONEncodable, Hashable {

    public var publishingChannels: [RenderablePublishingChannel]

    public init(publishingChannels: [RenderablePublishingChannel]) {
        self.publishingChannels = publishingChannels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannels, forKey: .publishingChannels)
    }
}

