//
// GetRecommendedPublishedItemsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRecommendedPublishedItemsSuccess: Codable, JSONEncodable, Hashable {

    public var renderablePublishedItems: [RenderablePublishedItem]

    public init(renderablePublishedItems: [RenderablePublishedItem]) {
        self.renderablePublishedItems = renderablePublishedItems
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case renderablePublishedItems
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(renderablePublishedItems, forKey: .renderablePublishedItems)
    }
}

