//
// GetUserProfileFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetUserProfileFailedReason: String, Codable, CaseIterable {
    case blocked = "Blocked"
    case userNotFound = "User Not Found"
}
