//
// GetUsersByUsernamesFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetUsersByUsernamesFailedReason: String, Codable, CaseIterable {
    case userNotFound = "User Not Found"
}
