//
// GetUsersByIdsRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetUsersByIdsRequestBody: Codable, JSONEncodable, Hashable {

    public var userIds: [String]

    public init(userIds: [String]) {
        self.userIds = userIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userIds, forKey: .userIds)
    }
}

