//
// GetUsersByUsernamesRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetUsersByUsernamesRequestBody: Codable, JSONEncodable, Hashable {

    public var usernames: [String]

    public init(usernames: [String]) {
        self.usernames = usernames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case usernames
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(usernames, forKey: .usernames)
    }
}

