//
// InviteUserToFollowPublishingChannelRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InviteUserToFollowPublishingChannelRequestBody: Codable, JSONEncodable, Hashable {

    public var invitedUserId: String
    public var publishingChannelId: String

    public init(invitedUserId: String, publishingChannelId: String) {
        self.invitedUserId = invitedUserId
        self.publishingChannelId = publishingChannelId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invitedUserId
        case publishingChannelId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invitedUserId, forKey: .invitedUserId)
        try container.encode(publishingChannelId, forKey: .publishingChannelId)
    }
}

