//
// IsPublishingChannelNameValidRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IsPublishingChannelNameValidRequestBody: Codable, JSONEncodable, Hashable {

    public var publishingChannelName: String

    public init(publishingChannelName: String) {
        self.publishingChannelName = publishingChannelName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannelName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannelName, forKey: .publishingChannelName)
    }
}

