//
// MakeCreditCardPrimaryRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MakeCreditCardPrimaryRequestBody: Codable, JSONEncodable, Hashable {

    public var localCreditCardId: String

    public init(localCreditCardId: String) {
        self.localCreditCardId = localCreditCardId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case localCreditCardId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(localCreditCardId, forKey: .localCreditCardId)
    }
}

