//
// MarkChatRoomAsReadSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MarkChatRoomAsReadSuccess: Codable, JSONEncodable, Hashable {

    public var countOfUnreadChatRooms: Double

    public init(countOfUnreadChatRooms: Double) {
        self.countOfUnreadChatRooms = countOfUnreadChatRooms
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case countOfUnreadChatRooms
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(countOfUnreadChatRooms, forKey: .countOfUnreadChatRooms)
    }
}

