//
// MediaElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MediaElement: Codable, JSONEncodable, Hashable {

    public var temporaryUrl: String
    public var mimeType: String

    public init(temporaryUrl: String, mimeType: String) {
        self.temporaryUrl = temporaryUrl
        self.mimeType = mimeType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case temporaryUrl
        case mimeType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(temporaryUrl, forKey: .temporaryUrl)
        try container.encode(mimeType, forKey: .mimeType)
    }
}

