//
// NewChatMessageNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NewChatMessageNotification: Codable, JSONEncodable, Hashable {

    public var countOfUnreadChatRooms: Double
    public var chatMessage: RenderableChatMessage

    public init(countOfUnreadChatRooms: Double, chatMessage: RenderableChatMessage) {
        self.countOfUnreadChatRooms = countOfUnreadChatRooms
        self.chatMessage = chatMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case countOfUnreadChatRooms
        case chatMessage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(countOfUnreadChatRooms, forKey: .countOfUnreadChatRooms)
        try container.encode(chatMessage, forKey: .chatMessage)
    }
}

