//
// NOTIFICATIONEVENTSNEWFOLLOWER.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSNEWFOLLOWER: String, Codable, CaseIterable {
    case newFollower = "NEW_FOLLOWER"
}
