//
// NOTIFICATIONEVENTSACCEPTEDUSERFOLLOWREQUEST.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSACCEPTEDUSERFOLLOWREQUEST: String, Codable, CaseIterable {
    case acceptedUserFollowRequest = "ACCEPTED_USER_FOLLOW_REQUEST"
}
