//
// NOTIFICATIONEVENTSSHOPITEMSOLD.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSSHOPITEMSOLD: String, Codable, CaseIterable {
    case shopItemSold = "SHOP_ITEM_SOLD"
}
