//
// NOTIFICATIONEVENTSNEWLIKEONPUBLISHEDITEM.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSNEWLIKEONPUBLISHEDITEM: String, Codable, CaseIterable {
    case newLikeOnPublishedItem = "NEW_LIKE_ON_PUBLISHED_ITEM"
}
