//
// NOTIFICATIONEVENTSINVITEDTOFOLLOWPUBLISHINGCHANNEL.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSINVITEDTOFOLLOWPUBLISHINGCHANNEL: String, Codable, CaseIterable {
    case invitedToFollowPublishingChannel = "INVITED_TO_FOLLOW_PUBLISHING_CHANNEL"
}
