//
// NOTIFICATIONEVENTSNEWSHAREOFPUBLISHEDITEM.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSNEWSHAREOFPUBLISHEDITEM: String, Codable, CaseIterable {
    case newShareOfPublishedItem = "NEW_SHARE_OF_PUBLISHED_ITEM"
}
