//
// NOTIFICATIONEVENTSNEWTAGINPUBLISHEDITEMCOMMENT.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSNEWTAGINPUBLISHEDITEMCOMMENT: String, Codable, CaseIterable {
    case newTagInPublishedItemComment = "NEW_TAG_IN_PUBLISHED_ITEM_COMMENT"
}
