//
// NOTIFICATIONEVENTSACCEPTEDPUBLISHINGCHANNELSUBMISSION.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSACCEPTEDPUBLISHINGCHANNELSUBMISSION: String, Codable, CaseIterable {
    case acceptedPublishingChannelSubmission = "ACCEPTED_PUBLISHING_CHANNEL_SUBMISSION"
}
