//
// NOTIFICATIONEVENTSNEWCOMMENTONPUBLISHEDITEM.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSNEWCOMMENTONPUBLISHEDITEM: String, Codable, CaseIterable {
    case newCommentOnPublishedItem = "NEW_COMMENT_ON_PUBLISHED_ITEM"
}
