//
// NOTIFICATIONEVENTSREJECTEDPUBLISHINGCHANNELSUBMISSION.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSREJECTEDPUBLISHINGCHANNELSUBMISSION: String, Codable, CaseIterable {
    case rejectedPublishingChannelSubmission = "REJECTED_PUBLISHING_CHANNEL_SUBMISSION"
}
