//
// NOTIFICATIONEVENTSNEWTAGINPUBLISHEDITEMCAPTION.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSNEWTAGINPUBLISHEDITEMCAPTION: String, Codable, CaseIterable {
    case newTagInPublishedItemCaption = "NEW_TAG_IN_PUBLISHED_ITEM_CAPTION"
}
