//
// NOTIFICATIONEVENTSNEWUSERFOLLOWREQUEST.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTSNEWUSERFOLLOWREQUEST: String, Codable, CaseIterable {
    case newUserFollowRequest = "NEW_USER_FOLLOW_REQUEST"
}
