//
// NOTIFICATIONEVENTS.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NOTIFICATIONEVENTS: String, Codable, CaseIterable {
    case deletedChatMessage = "DELETED_CHAT_MESSAGE"
    case newChatMessage = "NEW_CHAT_MESSAGE"
    case acceptedUserFollowRequest = "ACCEPTED_USER_FOLLOW_REQUEST"
    case canceledAcceptedUserFollowRequest = "CANCELED_ACCEPTED_USER_FOLLOW_REQUEST"
    case newFollower = "NEW_FOLLOWER"
    case canceledNewFollower = "CANCELED_NEW_FOLLOWER"
    case newUserFollowRequest = "NEW_USER_FOLLOW_REQUEST"
    case canceledNewUserFollowRequest = "CANCELED_NEW_USER_FOLLOW_REQUEST"
    case newCommentOnPublishedItem = "NEW_COMMENT_ON_PUBLISHED_ITEM"
    case canceledNewCommentOnPublishedItem = "CANCELED_NEW_COMMENT_ON_PUBLISHED_ITEM"
    case newLikeOnPublishedItem = "NEW_LIKE_ON_PUBLISHED_ITEM"
    case canceledNewLikeOnPublishedItem = "CANCELED_NEW_LIKE_ON_PUBLISHED_ITEM"
    case newShareOfPublishedItem = "NEW_SHARE_OF_PUBLISHED_ITEM"
    case canceledNewShareOfPublishedItem = "CANCELED_NEW_SHARE_OF_PUBLISHED_ITEM"
    case newTagInPublishedItemCaption = "NEW_TAG_IN_PUBLISHED_ITEM_CAPTION"
    case canceledNewTagInPublishedItemCaption = "CANCELED_NEW_TAG_IN_PUBLISHED_ITEM_CAPTION"
    case newTagInPublishedItemComment = "NEW_TAG_IN_PUBLISHED_ITEM_COMMENT"
    case canceledNewTagInPublishedItemComment = "CANCELED_NEW_TAG_IN_PUBLISHED_ITEM_COMMENT"
    case acceptedPublishingChannelSubmission = "ACCEPTED_PUBLISHING_CHANNEL_SUBMISSION"
    case rejectedPublishingChannelSubmission = "REJECTED_PUBLISHING_CHANNEL_SUBMISSION"
    case invitedToFollowPublishingChannel = "INVITED_TO_FOLLOW_PUBLISHING_CHANNEL"
    case shopItemSold = "SHOP_ITEM_SOLD"
    case newPublishedItem = "NEW_PUBLISHED_ITEM"
}
