//
// ProfilePrivacySetting.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ProfilePrivacySetting: String, Codable, CaseIterable {
    case _public = "Public"
    case _private = "Private"
}
