//
// PublishedItemTypePOST.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PublishedItemTypePOST: String, Codable, CaseIterable {
    case post = "POST"
}
