//
// PublishedItemHostAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PublishedItemHostAnyOf: String, Codable, CaseIterable {
    case userSelfHosted = "user-self-hosted"
}
