//
// PublishedItemTypeSHOPITEM.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PublishedItemTypeSHOPITEM: String, Codable, CaseIterable {
    case shopItem = "SHOP_ITEM"
}
