//
// PublishedItemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PublishedItemType: String, Codable, CaseIterable {
    case post = "POST"
    case shopItem = "SHOP_ITEM"
}
