//
// PurchaseShopItemRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PurchaseShopItemRequestBody: Codable, JSONEncodable, Hashable {

    public var publishedItemId: String
    public var localCreditCardId: String

    public init(publishedItemId: String, localCreditCardId: String) {
        self.publishedItemId = publishedItemId
        self.localCreditCardId = localCreditCardId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItemId
        case localCreditCardId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItemId, forKey: .publishedItemId)
        try container.encode(localCreditCardId, forKey: .localCreditCardId)
    }
}

