//
// ReadPageOfCommentsByPublishedItemIdRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReadPageOfCommentsByPublishedItemIdRequestBody: Codable, JSONEncodable, Hashable {

    public var publishedItemId: String
    public var cursor: String?
    public var pageSize: Double

    public init(publishedItemId: String, cursor: String? = nil, pageSize: Double) {
        self.publishedItemId = publishedItemId
        self.cursor = cursor
        self.pageSize = pageSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItemId
        case cursor
        case pageSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItemId, forKey: .publishedItemId)
        try container.encodeIfPresent(cursor, forKey: .cursor)
        try container.encode(pageSize, forKey: .pageSize)
    }
}

