//
// RegisterUserFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RegisterUserFailedReason: String, Codable, CaseIterable {
    case unknownCause = "Unknown Cause"
    case usernamesMayOnlyIncludeLowercaseEnglishLettersCommaDigitsCommaHyphensCommaAndUnderscores = "Usernames may only include lowercase English letters, digits, hyphens, and underscores"
}
