//
// RegisterUserRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterUserRequestBody: Codable, JSONEncodable, Hashable {

    public var email: String
    public var password: String
    public var username: String

    public init(email: String, password: String, username: String) {
        self.email = email
        self.password = password
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encode(username, forKey: .username)
    }
}

