//
// RemoveModeratorFromPublishingChannelFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RemoveModeratorFromPublishingChannelFailedReason: String, Codable, CaseIterable {
    case unknownCause = "Unknown Cause"
    case illegalAccess = "Illegal Access"
}
