//
// RenderableShopItemTypeSHOPITEMPREVIEW.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RenderableShopItemTypeSHOPITEMPREVIEW: String, Codable, CaseIterable {
    case shopItemPreview = "SHOP_ITEM_PREVIEW"
}
