//
// RenderableNewShareOfPublishedItemNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableNewShareOfPublishedItemNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTSNEWSHAREOFPUBLISHEDITEM
    public var countOfUnreadNotifications: Double
    public var eventTimestamp: Double
    public var timestampSeenByUser: Double?
    public var userSharingPublishedItem: RenderableUser
    public var sourcePublishedItem: RenderablePublishedItem
    public var newPublishedItemId: String

    public init(type: NOTIFICATIONEVENTSNEWSHAREOFPUBLISHEDITEM, countOfUnreadNotifications: Double, eventTimestamp: Double, timestampSeenByUser: Double? = nil, userSharingPublishedItem: RenderableUser, sourcePublishedItem: RenderablePublishedItem, newPublishedItemId: String) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.eventTimestamp = eventTimestamp
        self.timestampSeenByUser = timestampSeenByUser
        self.userSharingPublishedItem = userSharingPublishedItem
        self.sourcePublishedItem = sourcePublishedItem
        self.newPublishedItemId = newPublishedItemId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case eventTimestamp
        case timestampSeenByUser
        case userSharingPublishedItem
        case sourcePublishedItem
        case newPublishedItemId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(eventTimestamp, forKey: .eventTimestamp)
        try container.encodeIfPresent(timestampSeenByUser, forKey: .timestampSeenByUser)
        try container.encode(userSharingPublishedItem, forKey: .userSharingPublishedItem)
        try container.encode(sourcePublishedItem, forKey: .sourcePublishedItem)
        try container.encode(newPublishedItemId, forKey: .newPublishedItemId)
    }
}

