//
// RenderablePublishedItemComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderablePublishedItemComment: Codable, JSONEncodable, Hashable {

    public var publishedItemCommentId: String
    public var publishedItemId: String
    public var text: String
    public var authorUserId: String
    public var creationTimestamp: Double
    public var user: RenderableUser

    public init(publishedItemCommentId: String, publishedItemId: String, text: String, authorUserId: String, creationTimestamp: Double, user: RenderableUser) {
        self.publishedItemCommentId = publishedItemCommentId
        self.publishedItemId = publishedItemId
        self.text = text
        self.authorUserId = authorUserId
        self.creationTimestamp = creationTimestamp
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItemCommentId
        case publishedItemId
        case text
        case authorUserId
        case creationTimestamp
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItemCommentId, forKey: .publishedItemCommentId)
        try container.encode(publishedItemId, forKey: .publishedItemId)
        try container.encode(text, forKey: .text)
        try container.encode(authorUserId, forKey: .authorUserId)
        try container.encode(creationTimestamp, forKey: .creationTimestamp)
        try container.encode(user, forKey: .user)
    }
}

