//
// RenderableInvitedToFollowPublishingChannelNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableInvitedToFollowPublishingChannelNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTSINVITEDTOFOLLOWPUBLISHINGCHANNEL
    public var countOfUnreadNotifications: Double
    public var eventTimestamp: Double
    public var timestampSeenByUser: Double?
    public var userSendingInvitation: RenderableUser
    public var publishingChannel: RenderablePublishingChannel

    public init(type: NOTIFICATIONEVENTSINVITEDTOFOLLOWPUBLISHINGCHANNEL, countOfUnreadNotifications: Double, eventTimestamp: Double, timestampSeenByUser: Double? = nil, userSendingInvitation: RenderableUser, publishingChannel: RenderablePublishingChannel) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.eventTimestamp = eventTimestamp
        self.timestampSeenByUser = timestampSeenByUser
        self.userSendingInvitation = userSendingInvitation
        self.publishingChannel = publishingChannel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case eventTimestamp
        case timestampSeenByUser
        case userSendingInvitation
        case publishingChannel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(eventTimestamp, forKey: .eventTimestamp)
        try container.encodeIfPresent(timestampSeenByUser, forKey: .timestampSeenByUser)
        try container.encode(userSendingInvitation, forKey: .userSendingInvitation)
        try container.encode(publishingChannel, forKey: .publishingChannel)
    }
}

