//
// RenderableRejectedPublishingChannelSubmissionNotificationRejectionSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableRejectedPublishingChannelSubmissionNotificationRejectionSummary: Codable, JSONEncodable, Hashable {

    public var rejectionReason: String

    public init(rejectionReason: String) {
        self.rejectionReason = rejectionReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rejectionReason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rejectionReason, forKey: .rejectionReason)
    }
}

