//
// RenderableAcceptedUserFollowRequestNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableAcceptedUserFollowRequestNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTSACCEPTEDUSERFOLLOWREQUEST
    public var countOfUnreadNotifications: Double
    public var eventTimestamp: Double
    public var timestampSeenByUser: Double?
    public var userAcceptingFollowRequest: RenderableUser

    public init(type: NOTIFICATIONEVENTSACCEPTEDUSERFOLLOWREQUEST, countOfUnreadNotifications: Double, eventTimestamp: Double, timestampSeenByUser: Double? = nil, userAcceptingFollowRequest: RenderableUser) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.eventTimestamp = eventTimestamp
        self.timestampSeenByUser = timestampSeenByUser
        self.userAcceptingFollowRequest = userAcceptingFollowRequest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case eventTimestamp
        case timestampSeenByUser
        case userAcceptingFollowRequest
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(eventTimestamp, forKey: .eventTimestamp)
        try container.encodeIfPresent(timestampSeenByUser, forKey: .timestampSeenByUser)
        try container.encode(userAcceptingFollowRequest, forKey: .userAcceptingFollowRequest)
    }
}

