//
// RenderableNewCommentOnPublishedItemNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableNewCommentOnPublishedItemNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTSNEWCOMMENTONPUBLISHEDITEM
    public var countOfUnreadNotifications: Double
    public var eventTimestamp: Double
    public var timestampSeenByUser: Double?
    public var userThatCommented: RenderableUser
    public var publishedItem: RenderablePublishedItem
    public var publishedItemComment: RenderablePublishedItemComment

    public init(type: NOTIFICATIONEVENTSNEWCOMMENTONPUBLISHEDITEM, countOfUnreadNotifications: Double, eventTimestamp: Double, timestampSeenByUser: Double? = nil, userThatCommented: RenderableUser, publishedItem: RenderablePublishedItem, publishedItemComment: RenderablePublishedItemComment) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.eventTimestamp = eventTimestamp
        self.timestampSeenByUser = timestampSeenByUser
        self.userThatCommented = userThatCommented
        self.publishedItem = publishedItem
        self.publishedItemComment = publishedItemComment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case eventTimestamp
        case timestampSeenByUser
        case userThatCommented
        case publishedItem
        case publishedItemComment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(eventTimestamp, forKey: .eventTimestamp)
        try container.encodeIfPresent(timestampSeenByUser, forKey: .timestampSeenByUser)
        try container.encode(userThatCommented, forKey: .userThatCommented)
        try container.encode(publishedItem, forKey: .publishedItem)
        try container.encode(publishedItemComment, forKey: .publishedItemComment)
    }
}

