//
// RenderableShopItemSoldNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableShopItemSoldNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTSSHOPITEMSOLD
    public var countOfUnreadNotifications: Double
    public var eventTimestamp: Double
    public var timestampSeenByUser: Double?
    public var purchaser: RenderableUser
    public var shopItem: RenderableShopItem

    public init(type: NOTIFICATIONEVENTSSHOPITEMSOLD, countOfUnreadNotifications: Double, eventTimestamp: Double, timestampSeenByUser: Double? = nil, purchaser: RenderableUser, shopItem: RenderableShopItem) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.eventTimestamp = eventTimestamp
        self.timestampSeenByUser = timestampSeenByUser
        self.purchaser = purchaser
        self.shopItem = shopItem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case eventTimestamp
        case timestampSeenByUser
        case purchaser
        case shopItem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(eventTimestamp, forKey: .eventTimestamp)
        try container.encodeIfPresent(timestampSeenByUser, forKey: .timestampSeenByUser)
        try container.encode(purchaser, forKey: .purchaser)
        try container.encode(shopItem, forKey: .shopItem)
    }
}

