//
// RenderableChatRoomWithJoinedUsers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableChatRoomWithJoinedUsers: Codable, JSONEncodable, Hashable {

    public var chatRoomId: String
    public var members: [RenderableUser]
    public var hasUnreadMessages: Bool

    public init(chatRoomId: String, members: [RenderableUser], hasUnreadMessages: Bool) {
        self.chatRoomId = chatRoomId
        self.members = members
        self.hasUnreadMessages = hasUnreadMessages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatRoomId
        case members
        case hasUnreadMessages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatRoomId, forKey: .chatRoomId)
        try container.encode(members, forKey: .members)
        try container.encode(hasUnreadMessages, forKey: .hasUnreadMessages)
    }
}

