//
// RenderableShopItemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RenderableShopItemType: String, Codable, CaseIterable {
    case shopItemPreview = "SHOP_ITEM_PREVIEW"
    case purchasedShopItemDetails = "PURCHASED_SHOP_ITEM_DETAILS"
}
