//
// RenderableChatMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableChatMessage: Codable, JSONEncodable, Hashable {

    public var chatMessageId: String
    public var text: String
    public var authorUserId: String
    public var chatRoomId: String
    public var creationTimestamp: Double

    public init(chatMessageId: String, text: String, authorUserId: String, chatRoomId: String, creationTimestamp: Double) {
        self.chatMessageId = chatMessageId
        self.text = text
        self.authorUserId = authorUserId
        self.chatRoomId = chatRoomId
        self.creationTimestamp = creationTimestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatMessageId
        case text
        case authorUserId
        case chatRoomId
        case creationTimestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatMessageId, forKey: .chatMessageId)
        try container.encode(text, forKey: .text)
        try container.encode(authorUserId, forKey: .authorUserId)
        try container.encode(chatRoomId, forKey: .chatRoomId)
        try container.encode(creationTimestamp, forKey: .creationTimestamp)
    }
}

