//
// RenderableShopItemTypePURCHASEDSHOPITEMDETAILS.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RenderableShopItemTypePURCHASEDSHOPITEMDETAILS: String, Codable, CaseIterable {
    case purchasedShopItemDetails = "PURCHASED_SHOP_ITEM_DETAILS"
}
