//
// RenderableNewUserFollowRequestNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableNewUserFollowRequestNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTSNEWUSERFOLLOWREQUEST
    public var countOfUnreadNotifications: Double
    public var eventTimestamp: Double
    public var timestampSeenByUser: Double?
    public var followRequestingUser: RenderableUser

    public init(type: NOTIFICATIONEVENTSNEWUSERFOLLOWREQUEST, countOfUnreadNotifications: Double, eventTimestamp: Double, timestampSeenByUser: Double? = nil, followRequestingUser: RenderableUser) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.eventTimestamp = eventTimestamp
        self.timestampSeenByUser = timestampSeenByUser
        self.followRequestingUser = followRequestingUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case eventTimestamp
        case timestampSeenByUser
        case followRequestingUser
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(eventTimestamp, forKey: .eventTimestamp)
        try container.encodeIfPresent(timestampSeenByUser, forKey: .timestampSeenByUser)
        try container.encode(followRequestingUser, forKey: .followRequestingUser)
    }
}

