//
// RenderableRejectedPublishingChannelSubmissionNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenderableRejectedPublishingChannelSubmissionNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTSREJECTEDPUBLISHINGCHANNELSUBMISSION
    public var countOfUnreadNotifications: Double
    public var eventTimestamp: Double
    public var timestampSeenByUser: Double?
    public var publishedItem: RenderablePublishedItem
    public var publishingChannel: RenderablePublishingChannel
    public var rejectionSummary: RenderableRejectedPublishingChannelSubmissionNotificationRejectionSummary

    public init(type: NOTIFICATIONEVENTSREJECTEDPUBLISHINGCHANNELSUBMISSION, countOfUnreadNotifications: Double, eventTimestamp: Double, timestampSeenByUser: Double? = nil, publishedItem: RenderablePublishedItem, publishingChannel: RenderablePublishingChannel, rejectionSummary: RenderableRejectedPublishingChannelSubmissionNotificationRejectionSummary) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.eventTimestamp = eventTimestamp
        self.timestampSeenByUser = timestampSeenByUser
        self.publishedItem = publishedItem
        self.publishingChannel = publishingChannel
        self.rejectionSummary = rejectionSummary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case eventTimestamp
        case timestampSeenByUser
        case publishedItem
        case publishingChannel
        case rejectionSummary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(eventTimestamp, forKey: .eventTimestamp)
        try container.encodeIfPresent(timestampSeenByUser, forKey: .timestampSeenByUser)
        try container.encode(publishedItem, forKey: .publishedItem)
        try container.encode(publishingChannel, forKey: .publishingChannel)
        try container.encode(rejectionSummary, forKey: .rejectionSummary)
    }
}

