//
// ResetPasswordFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ResetPasswordFailedReason: String, Codable, CaseIterable {
    case invalidToken = "InvalidToken"
    case invalidPassword = "InvalidPassword"
}
