//
// ResolveAllFollowRequestsRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResolveAllFollowRequestsRequestBody: Codable, JSONEncodable, Hashable {

    public var decision: FollowAllRequestsDecision

    public init(decision: FollowAllRequestsDecision) {
        self.decision = decision
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case decision
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(decision, forKey: .decision)
    }
}

