//
// ResolveFollowRequestRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResolveFollowRequestRequestBody: Codable, JSONEncodable, Hashable {

    public var decision: FollowRequestDecision
    public var userIdDoingFollowing: String

    public init(decision: FollowRequestDecision, userIdDoingFollowing: String) {
        self.decision = decision
        self.userIdDoingFollowing = userIdDoingFollowing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case decision
        case userIdDoingFollowing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(decision, forKey: .decision)
        try container.encode(userIdDoingFollowing, forKey: .userIdDoingFollowing)
    }
}

