//
// SearchForUsersSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchForUsersSuccess: Codable, JSONEncodable, Hashable {

    public var users: [RenderableUser]
    public var totalCount: Double

    public init(users: [RenderableUser], totalCount: Double) {
        self.users = users
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(users, forKey: .users)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

