//
// SearchForPostsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchForPostsSuccess: Codable, JSONEncodable, Hashable {

    public var posts: [RenderablePost]
    public var totalCount: Double

    public init(posts: [RenderablePost], totalCount: Double) {
        self.posts = posts
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case posts
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(posts, forKey: .posts)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

