//
// SearchForHashtagsRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchForHashtagsRequestBody: Codable, JSONEncodable, Hashable {

    public var query: String
    public var pageNumber: Double
    public var pageSize: Double

    public init(query: String, pageNumber: Double, pageSize: Double) {
        self.query = query
        self.pageNumber = pageNumber
        self.pageSize = pageSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
        case pageNumber
        case pageSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(query, forKey: .query)
        try container.encode(pageNumber, forKey: .pageNumber)
        try container.encode(pageSize, forKey: .pageSize)
    }
}

