//
// SearchUserProfilesByUsernameFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SearchUserProfilesByUsernameFailedReason: String, Codable, CaseIterable {
    case userNotFound = "User Not Found"
}
