//
// SearchForPublishingChannelsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchForPublishingChannelsSuccess: Codable, JSONEncodable, Hashable {

    public var publishingChannels: [RenderablePublishingChannel]
    public var totalCount: Double

    public init(publishingChannels: [RenderablePublishingChannel], totalCount: Double) {
        self.publishingChannels = publishingChannels
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannels
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannels, forKey: .publishingChannels)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

