//
// SearchUserProfilesByUsernameRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchUserProfilesByUsernameRequestBody: Codable, JSONEncodable, Hashable {

    public var searchString: String

    public init(searchString: String) {
        self.searchString = searchString
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searchString
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(searchString, forKey: .searchString)
    }
}

