//
// SearchForHashtagsSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchForHashtagsSuccess: Codable, JSONEncodable, Hashable {

    public var hashtags: [String]
    public var totalCount: Double

    public init(hashtags: [String], totalCount: Double) {
        self.hashtags = hashtags
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hashtags
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hashtags, forKey: .hashtags)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

