//
// SendDataTypesToFrontend1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendDataTypesToFrontend1Request: Codable, JSONEncodable, Hashable {

    public var newChatMessageNotification: NewChatMessageNotification
    public var unrenderableCanceledNewLikeOnPostNotification: UnrenderableCanceledNewLikeOnPublishedItemNotification
    public var unrenderableCanceledNewFollowerNotification: UnrenderableCanceledNewFollowerNotification
    public var unrenderableCanceledCommentOnPostNotification: UnrenderableCanceledNewCommentOnPublishedItemNotification

    public init(newChatMessageNotification: NewChatMessageNotification, unrenderableCanceledNewLikeOnPostNotification: UnrenderableCanceledNewLikeOnPublishedItemNotification, unrenderableCanceledNewFollowerNotification: UnrenderableCanceledNewFollowerNotification, unrenderableCanceledCommentOnPostNotification: UnrenderableCanceledNewCommentOnPublishedItemNotification) {
        self.newChatMessageNotification = newChatMessageNotification
        self.unrenderableCanceledNewLikeOnPostNotification = unrenderableCanceledNewLikeOnPostNotification
        self.unrenderableCanceledNewFollowerNotification = unrenderableCanceledNewFollowerNotification
        self.unrenderableCanceledCommentOnPostNotification = unrenderableCanceledCommentOnPostNotification
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newChatMessageNotification = "NewChatMessageNotification"
        case unrenderableCanceledNewLikeOnPostNotification = "UnrenderableCanceledNewLikeOnPostNotification"
        case unrenderableCanceledNewFollowerNotification = "UnrenderableCanceledNewFollowerNotification"
        case unrenderableCanceledCommentOnPostNotification = "UnrenderableCanceledCommentOnPostNotification"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(newChatMessageNotification, forKey: .newChatMessageNotification)
        try container.encode(unrenderableCanceledNewLikeOnPostNotification, forKey: .unrenderableCanceledNewLikeOnPostNotification)
        try container.encode(unrenderableCanceledNewFollowerNotification, forKey: .unrenderableCanceledNewFollowerNotification)
        try container.encode(unrenderableCanceledCommentOnPostNotification, forKey: .unrenderableCanceledCommentOnPostNotification)
    }
}

