//
// SetUserContentFeedFiltersRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetUserContentFeedFiltersRequestBody: Codable, JSONEncodable, Hashable {

    public var requestedContentFeedFilters: [UserContentFeedFilter]

    public init(requestedContentFeedFilters: [UserContentFeedFilter]) {
        self.requestedContentFeedFilters = requestedContentFeedFilters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestedContentFeedFilters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestedContentFeedFilters, forKey: .requestedContentFeedFilters)
    }
}

