//
// SetUserHashtagsRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetUserHashtagsRequestBody: Codable, JSONEncodable, Hashable {

    public var hashtags: [String]

    public init(hashtags: [String]) {
        self.hashtags = hashtags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hashtags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hashtags, forKey: .hashtags)
    }
}

