//
// SharePostRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SharePostRequestBody: Codable, JSONEncodable, Hashable {

    public var sharedPublishedItemId: String
    public var caption: String
    public var hashtags: [String]
    public var scheduledPublicationTimestamp: Double?
    public var expirationTimestamp: Double?

    public init(sharedPublishedItemId: String, caption: String, hashtags: [String], scheduledPublicationTimestamp: Double? = nil, expirationTimestamp: Double? = nil) {
        self.sharedPublishedItemId = sharedPublishedItemId
        self.caption = caption
        self.hashtags = hashtags
        self.scheduledPublicationTimestamp = scheduledPublicationTimestamp
        self.expirationTimestamp = expirationTimestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sharedPublishedItemId
        case caption
        case hashtags
        case scheduledPublicationTimestamp
        case expirationTimestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sharedPublishedItemId, forKey: .sharedPublishedItemId)
        try container.encode(caption, forKey: .caption)
        try container.encode(hashtags, forKey: .hashtags)
        try container.encodeIfPresent(scheduledPublicationTimestamp, forKey: .scheduledPublicationTimestamp)
        try container.encodeIfPresent(expirationTimestamp, forKey: .expirationTimestamp)
    }
}

