//
// StoreCreditCardSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StoreCreditCardSuccess: Codable, JSONEncodable, Hashable {

    public var userId: String
    public var localCreditCardId: String
    public var paymentProcessorCardId: String
    public var creationTimestamp: Double
    public var isPrimaryCard: Bool

    public init(userId: String, localCreditCardId: String, paymentProcessorCardId: String, creationTimestamp: Double, isPrimaryCard: Bool) {
        self.userId = userId
        self.localCreditCardId = localCreditCardId
        self.paymentProcessorCardId = paymentProcessorCardId
        self.creationTimestamp = creationTimestamp
        self.isPrimaryCard = isPrimaryCard
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case localCreditCardId
        case paymentProcessorCardId
        case creationTimestamp
        case isPrimaryCard
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(localCreditCardId, forKey: .localCreditCardId)
        try container.encode(paymentProcessorCardId, forKey: .paymentProcessorCardId)
        try container.encode(creationTimestamp, forKey: .creationTimestamp)
        try container.encode(isPrimaryCard, forKey: .isPrimaryCard)
    }
}

