//
// StoreCreditCardFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum StoreCreditCardFailedReason: String, Codable, CaseIterable {
    case unknownReason = "UNKNOWN_REASON"
}
