//
// SubmitPublishedItemToPublishingChannelRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubmitPublishedItemToPublishingChannelRequestBody: Codable, JSONEncodable, Hashable {

    public var publishingChannelId: String
    public var publishedItemId: String

    public init(publishingChannelId: String, publishedItemId: String) {
        self.publishingChannelId = publishingChannelId
        self.publishedItemId = publishedItemId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannelId
        case publishedItemId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannelId, forKey: .publishingChannelId)
        try container.encode(publishedItemId, forKey: .publishedItemId)
    }
}

