//
// UnblockUserRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UnblockUserRequestBody: Codable, JSONEncodable, Hashable {

    public var blockedUserId: String

    public init(blockedUserId: String) {
        self.blockedUserId = blockedUserId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockedUserId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockedUserId, forKey: .blockedUserId)
    }
}

