//
// UnfollowPublishingChannelRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UnfollowPublishingChannelRequestBody: Codable, JSONEncodable, Hashable {

    public var publishingChannelIdBeingUnfollowed: String

    public init(publishingChannelIdBeingUnfollowed: String) {
        self.publishingChannelIdBeingUnfollowed = publishingChannelIdBeingUnfollowed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishingChannelIdBeingUnfollowed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishingChannelIdBeingUnfollowed, forKey: .publishingChannelIdBeingUnfollowed)
    }
}

