//
// UnfollowPublishingChannelFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum UnfollowPublishingChannelFailedReason: String, Codable, CaseIterable {
    case unknownCause = "Unknown Cause"
    case canNotUnfollowOwnChannel = "CAN_NOT_UNFOLLOW_OWN_CHANNEL"
}
