//
// UnfollowUserRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UnfollowUserRequestBody: Codable, JSONEncodable, Hashable {

    public var userIdBeingUnfollowed: String

    public init(userIdBeingUnfollowed: String) {
        self.userIdBeingUnfollowed = userIdBeingUnfollowed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userIdBeingUnfollowed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userIdBeingUnfollowed, forKey: .userIdBeingUnfollowed)
    }
}

