//
// UnrenderableCanceledNewLikeOnPublishedItemNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UnrenderableCanceledNewLikeOnPublishedItemNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTS
    public var countOfUnreadNotifications: Double
    public var userIdUnlikingPublishedItem: String
    public var publishedItemId: String

    public init(type: NOTIFICATIONEVENTS, countOfUnreadNotifications: Double, userIdUnlikingPublishedItem: String, publishedItemId: String) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.userIdUnlikingPublishedItem = userIdUnlikingPublishedItem
        self.publishedItemId = publishedItemId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case userIdUnlikingPublishedItem
        case publishedItemId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(userIdUnlikingPublishedItem, forKey: .userIdUnlikingPublishedItem)
        try container.encode(publishedItemId, forKey: .publishedItemId)
    }
}

