//
// UnrenderableCanceledNewCommentOnPublishedItemNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UnrenderableCanceledNewCommentOnPublishedItemNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTS
    public var countOfUnreadNotifications: Double
    public var publishedItemCommentId: String

    public init(type: NOTIFICATIONEVENTS, countOfUnreadNotifications: Double, publishedItemCommentId: String) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.publishedItemCommentId = publishedItemCommentId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case publishedItemCommentId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(publishedItemCommentId, forKey: .publishedItemCommentId)
    }
}

