//
// UnrenderableCanceledNewFollowerNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UnrenderableCanceledNewFollowerNotification: Codable, JSONEncodable, Hashable {

    public var type: NOTIFICATIONEVENTS
    public var countOfUnreadNotifications: Double
    public var userIdDoingUnfollowing: String

    public init(type: NOTIFICATIONEVENTS, countOfUnreadNotifications: Double, userIdDoingUnfollowing: String) {
        self.type = type
        self.countOfUnreadNotifications = countOfUnreadNotifications
        self.userIdDoingUnfollowing = userIdDoingUnfollowing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case countOfUnreadNotifications
        case userIdDoingUnfollowing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(countOfUnreadNotifications, forKey: .countOfUnreadNotifications)
        try container.encode(userIdDoingUnfollowing, forKey: .userIdDoingUnfollowing)
    }
}

