//
// UpdatePublishingChannelProfilePictureFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum UpdatePublishingChannelProfilePictureFailedReason: String, Codable, CaseIterable {
    case unknown = "Unknown"
    case illegalAccess = "ILLEGAL_ACCESS"
}
