//
// UpdatePublishingChannelBackgroundImageRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdatePublishingChannelBackgroundImageRequestBody: Codable, JSONEncodable, Hashable {

    public var backgroundImage: FileDescriptor
    public var publishingChannelId: String

    public init(backgroundImage: FileDescriptor, publishingChannelId: String) {
        self.backgroundImage = backgroundImage
        self.publishingChannelId = publishingChannelId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case backgroundImage
        case publishingChannelId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(backgroundImage, forKey: .backgroundImage)
        try container.encode(publishingChannelId, forKey: .publishingChannelId)
    }
}

