//
// UpdateUserBackgroundImageRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateUserBackgroundImageRequestBody: Codable, JSONEncodable, Hashable {

    public var backgroundImage: FileDescriptor

    public init(backgroundImage: FileDescriptor) {
        self.backgroundImage = backgroundImage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case backgroundImage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(backgroundImage, forKey: .backgroundImage)
    }
}

