//
// UpdateUserProfileRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateUserProfileRequestBody: Codable, JSONEncodable, Hashable {

    public var username: String
    public var shortBio: String
    public var userWebsite: String
    public var userEmail: String
    public var phoneNumber: String
    public var preferredPagePrimaryColor: Color
    public var profileVisibility: ProfilePrivacySetting

    public init(username: String, shortBio: String, userWebsite: String, userEmail: String, phoneNumber: String, preferredPagePrimaryColor: Color, profileVisibility: ProfilePrivacySetting) {
        self.username = username
        self.shortBio = shortBio
        self.userWebsite = userWebsite
        self.userEmail = userEmail
        self.phoneNumber = phoneNumber
        self.preferredPagePrimaryColor = preferredPagePrimaryColor
        self.profileVisibility = profileVisibility
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case shortBio
        case userWebsite
        case userEmail
        case phoneNumber
        case preferredPagePrimaryColor
        case profileVisibility
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(shortBio, forKey: .shortBio)
        try container.encode(userWebsite, forKey: .userWebsite)
        try container.encode(userEmail, forKey: .userEmail)
        try container.encode(phoneNumber, forKey: .phoneNumber)
        try container.encode(preferredPagePrimaryColor, forKey: .preferredPagePrimaryColor)
        try container.encode(profileVisibility, forKey: .profileVisibility)
    }
}

