//
// UpdatePublishingChannelProfilePictureRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdatePublishingChannelProfilePictureRequestBody: Codable, JSONEncodable, Hashable {

    public var profilePicture: FileDescriptor
    public var publishingChannelId: String

    public init(profilePicture: FileDescriptor, publishingChannelId: String) {
        self.profilePicture = profilePicture
        self.publishingChannelId = publishingChannelId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profilePicture
        case publishingChannelId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profilePicture, forKey: .profilePicture)
        try container.encode(publishingChannelId, forKey: .publishingChannelId)
    }
}

