//
// UpdatePasswordFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum UpdatePasswordFailedReason: String, Codable, CaseIterable {
    case unknown = "Unknown"
    case databaseError = "Database Error"
}
