//
// UpdatePublishingChannelFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum UpdatePublishingChannelFailedReason: String, Codable, CaseIterable {
    case unknown = "Unknown"
    case publishingChannelIdNotFound = "PublishingChannelIdNotFound"
    case illegalAccess = "IllegalAccess"
}
