//
// UpdatePostRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdatePostRequestBody: Codable, JSONEncodable, Hashable {

    public var publishedItemId: String
    public var caption: String?
    public var scheduledPublicationTimestamp: Double?
    public var expirationTimestamp: Double?

    public init(publishedItemId: String, caption: String? = nil, scheduledPublicationTimestamp: Double? = nil, expirationTimestamp: Double? = nil) {
        self.publishedItemId = publishedItemId
        self.caption = caption
        self.scheduledPublicationTimestamp = scheduledPublicationTimestamp
        self.expirationTimestamp = expirationTimestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publishedItemId
        case caption
        case scheduledPublicationTimestamp
        case expirationTimestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publishedItemId, forKey: .publishedItemId)
        try container.encodeIfPresent(caption, forKey: .caption)
        try container.encodeIfPresent(scheduledPublicationTimestamp, forKey: .scheduledPublicationTimestamp)
        try container.encodeIfPresent(expirationTimestamp, forKey: .expirationTimestamp)
    }
}

