//
// UpdateUserProfilePictureFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum UpdateUserProfilePictureFailedReason: String, Codable, CaseIterable {
    case unknown = "Unknown"
}
