//
// UpdateShopItemFailedReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum UpdateShopItemFailedReason: String, Codable, CaseIterable {
    case illegalAccess = "Illegal Access"
}
