//
// UpdatePasswordRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdatePasswordRequestBody: Codable, JSONEncodable, Hashable {

    public var updatedPassword: String

    public init(updatedPassword: String) {
        self.updatedPassword = updatedPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updatedPassword
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(updatedPassword, forKey: .updatedPassword)
    }
}

