//
// UploadFileSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UploadFileSuccess: Codable, JSONEncodable, Hashable {

    public var blobFileKey: String

    public init(blobFileKey: String) {
        self.blobFileKey = blobFileKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blobFileKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blobFileKey, forKey: .blobFileKey)
    }
}

