//
// UserContentFeedFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserContentFeedFilter: Codable, JSONEncodable, Hashable {

    public var contentFeedFilterId: String
    public var userId: String
    public var type: UserContentFeedFilterType
    public var value: String
    public var creationTimestamp: Double

    public init(contentFeedFilterId: String, userId: String, type: UserContentFeedFilterType, value: String, creationTimestamp: Double) {
        self.contentFeedFilterId = contentFeedFilterId
        self.userId = userId
        self.type = type
        self.value = value
        self.creationTimestamp = creationTimestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentFeedFilterId
        case userId
        case type
        case value
        case creationTimestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contentFeedFilterId, forKey: .contentFeedFilterId)
        try container.encode(userId, forKey: .userId)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
        try container.encode(creationTimestamp, forKey: .creationTimestamp)
    }
}

