//
// UserContentFeedFilterType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum UserContentFeedFilterType: String, Codable, CaseIterable {
    case hashtag = "HASHTAG"
    case username = "USERNAME"
    case publishingChannel = "PUBLISHING_CHANNEL"
    case followingUsers = "FOLLOWING_USERS"
    case allPostsForAdmins = "ALL_POSTS_FOR_ADMINS"
}
