export enum NOTIFICATION_EVENTS {
  // CHAT
  DELETED_CHAT_MESSAGE = "DELETED_CHAT_MESSAGE",
  NEW_CHAT_MESSAGE = "NEW_CHAT_MESSAGE",

  // USER NOTIFICATION
  NEW_COMMENT_ON_PUBLISHED_ITEM = "NEW_COMMENT_ON_PUBLISHED_ITEM",
  CANCELED_NEW_COMMENT_ON_PUBLISHED_ITEM = "CANCELED_NEW_COMMENT_ON_PUBLISHED_ITEM",

  NEW_FOLLOWER = "NEW_FOLLOWER",
  CANCELED_NEW_FOLLOWER = "CANCELED_NEW_FOLLOWER",

  NEW_LIKE_ON_PUBLISHED_ITEM = "NEW_LIKE_ON_PUBLISHED_ITEM",
  CANCELED_NEW_LIKE_ON_PUBLISHED_ITEM = "CANCELED_NEW_LIKE_ON_PUBLISHED_ITEM",

  NEW_TAG_IN_PUBLISHED_ITEM_COMMENT = "NEW_TAG_IN_PUBLISHED_ITEM_COMMENT",
  CANCELED_NEW_TAG_IN_PUBLISHED_ITEM_COMMENT = "CANCELED_NEW_TAG_IN_PUBLISHED_ITEM_COMMENT",

  // OTHER
  NEW_PUBLISHED_ITEM = "NEW_PUBLISHED_ITEM",
}
